apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.backend.externalSecretName }}