apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homie-frontend
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - homie-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s